# Site settings
baseurl = "/"
languageCode = "en-us"
title = "Oran & Turgut"
theme = "infinity-hugo"

[params]
# Navigation
[params.navigation]
logo = "images/logo.png"
home = "Anasayfa"
about = "Hakkımızda"
service = "Hizmetlerimiz"
contact = "İletişim"

# Hero Area
[params.hero]
enable      = true
bg          = "images/justice.jpg"
title       = "ORAN & TURGUT HUKUK BÜROSU"
subtitle    = ""
btnText     = ""
countdownYear = ""
countdownMonth = ""
countdownDay  = ""

# About Section
[params.about]
enable      = true
heading     = "Lorem ipsum dolor sit amet, consectetur adipisicing elit. Magnam ipsa recusandae consequatur veniam, reiciendis odit quia eaque vel eius a."
description = "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ulla-mco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in Lorem ipsum dolor sit amet, consectetur adipisicing elit. Neque, aspernatur."

[[params.about.member]]
image   = "images/gulsumoran.png"
name    = "Gülsüm Oran"
title   = "Avukat"
phone   = "+90 538 476 16 66"
email   = "gulsum@oranturgut.com"

[[params.about.member]]
image   = "images/aliturgut.jpg"
name    = "Ali Turgut"
title   = "Avukat"
phone   = "+90 534 419 41 49"
email   = "ali@oranturgut.com"


# Service Section
[params.service]
enable      = true
title       = "Hukuki sorunlarınıza efektif çözümler"
subtitle    = ""

[[params.service.serviceItem]]
icon    = "tf-ion-android-people"
title   = "AİLE HUKUKU"
description = ""
delay   = "0s"

[[params.service.serviceItem]]
icon    = "tf-ion-android-alert"
title   = "CEZA HUKUKU"
description = ""
delay   = "0.2s"

[[params.service.serviceItem]]
icon    = "tf-ion-compose"
title   = "MİRAS HUKUKU"
description = ""
delay   = "0.4s"

[[params.service.serviceItem]]
icon    = "tf-ion-cash"
title   = "İCRA & İFLAS HUKUKU"
description = ""
delay   = "0.6s"

[[params.service.serviceItem]]
icon    = "tf-ion-ios-home"
title   = "SİGORTA HUKUKU"
description = ""
delay   = "0.8s"

[[params.service.serviceItem]]
icon    = "tf-ion-ios-briefcase"
title   = "İŞ HUKUKU"
description = ""
delay   = "1s"

[[params.service.serviceItem]]
icon    = "tf-ion-android-globe"
title   = "ULUSLARARASI HUKUK"
description = ""
delay   = "1.2s"

[[params.service.serviceItem]]
icon    = "tf-ion-arrow-graph-up-right"
title   = "TİCARET HUKUKU"
description = ""
delay   = "1.5s"

# Call to Action Section
[params.cta]
enable      = false
bg          = "images/call-to-action.jpg"
title       = "Subscribe to our mailing list"
subtitle    = "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod"

[params.contact]
enable      = false
title       = "Bize Ulaşın"
subtitle    = "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Utenim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex"
